spring.application.name=risk-simulator
spring.datasource.url=jdbc:postgresql://localhost:5432/risk_simulator
spring.datasource.username=postgres
spring.datasource.password=1253236

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081